### ISSUE TITLE
raster.input does not interpret tiff the same as gdal.input

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1520]
This is replicable with tiffs created from mapnik pngs and converted from png to tiff by imagemagick (`convert test.png test.tiff`), but not tiffs created using `gdal_translate`. Note: intentionally did not test with tiffs created directly by mapnik due to #1510.

The result below would be *expected* if the tiffs were premultiplied (associated alpha), but the reported info is `Extra Samples: 1<unassoc-alpha>` for the image magick tiff. The GDAL created one wrongly reports `assoc-alpha`.

```python
>>> import mapnik
>>> im = mapnik.Image(1,1)
>>> im.background = mapnik.Color('rgba(255,255,255,.5)')
>>> im.get_pixel(0,0)
2164260863
>>> pixel2channels(2164260863)
(255, 255, 255, 128)
>>> im.save('test.png')
>>> import os
>>> os.system('convert test.png test.tiff')
0
>>> im2 = mapnik.Image.open('test.tiff')
>>> im2.get_pixel(0,0)
2155905152
>>> pixel2channels(2155905152)
(128, 128, 128, 128)
```

Here is the tiff created with image magick: http://cl.ly/1N2w211E0k1W

`gdal_translate` create tiffs work...

```python
>>> os.system('gdal_translate test.png gdal.tiff')
Input file size is 1, 1
0...10...20...30...40...50...60...70...80...90...100 - done.
0
>>> im3 = mapnik.Image.open('gdal.tiff')
are_bytes_swapped: 0
>>> im3.get_pixel(0,0)
2164260863
>>> pixel2channels(2164260863)
(255, 255, 255, 128)
```
Here is the tiff created with gdal: http://cl.ly/0m0G3N2g3a1m

```python
def pixel2channels(pixel):
    alpha = (pixel >> 24) & 0xff
    red = pixel & 0xff
    green = (pixel >> 8) & 0xff
    blue = (pixel >> 16) & 0xff
    return red,green,blue,alpha
```

```
~/projects/mapnik5[master]$ file test.png
test.png: PNG image data, 1 x 1, 8-bit/color RGBA, non-interlaced
~/projects/mapnik5[master]$ file test.tiff
test.tiff: TIFF image data, little-endian
~/projects/mapnik5[master]$ tiffinfo test.tiff
TIFF Directory at offset 0x14 (20)
  Image Width: 1 Image Length: 1
  Resolution: 72, 72 (unitless)
  Bits/Sample: 8
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Rows/Strip: 1
  Planar Configuration: single image plane
  Page Number: 0-1
  DocumentName: test.tiff
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
  Predictor: horizontal differencing 2 (0x2)
~/projects/mapnik5[master]$ tiffinfo gdal.tiff
TIFF Directory at offset 0x8 (8)
  Image Width: 1 Image Length: 1
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Samples/Pixel: 4
  Rows/Strip: 1
  Planar Configuration: single image plane
```

**Comment by flippmoke** [comment]
Could this have been related to the UNASSALPHA vs ASSOCALPHA tiff issues we have looked into recently @springmeyer ?

**Comment by springmeyer** [comment]
@flippmoke definitely seems related. Hopefully your work will get to the bottom of this. Btw, this issues was uncovered when solving #1512.

**Comment by flippmoke** [comment]
I have found that using `TIFFReadRGBATile` and `TIFFReadRGBAStripped` will always return a premultiplied alpha. They are located [here](https://github.com/mapnik/mapnik/blob/93f67f9bc9ee40b050aab705841b1364ac1653eb/src/tiff_reader.cpp#L474) and [here](https://github.com/mapnik/mapnik/blob/93f67f9bc9ee40b050aab705841b1364ac1653eb/src/tiff_reader.cpp#L661) in our code currently.

If the TIFF is only 3 bands, RGB, then the methods will return an alpha of 255. In this case the image could already be treated as premultiplied.

If TIFF has 4 bands and has the [extrasamples](http://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html) tag of `EXTRASAMPLE_UNSPECIFIED` or `EXTRASAMPLE_ASSOCALPHA` will result in the two methods listed above to simply returning the values of the 4 as RGBA. In this case we can treat them as already premultiplied as `EXTRASAMPLE_ASSOCALPHA`.

> Associated alpha is generally interpreted as true transparancy information. Indeed, the original color values are lost in the case of complete transparency, and rounded in the case of partial transparency. Also, associated alpha is only logically possible as the single extra channel.

If the extrasample is defined as `EXTRASAMPLE_UNASSALPHA` the two methods above will automatically premultiply the data within the file prior to returning it. Currently in our [code](https://github.com/mapnik/mapnik/blob/93f67f9bc9ee40b050aab705841b1364ac1653eb/src/tiff_reader.cpp#L309) it is only considered premultiplied when `EXTRASAMPLE_ASSOCALPHA` is tagged. This means that we passing an `EXTRASAMPLE_UNASSALPHA` tiff to our renderer it will be premultiplied again. This has been confusing because there is no mention of this in the documentation from what I have seen. Additionally, reading the description of `EXTRASAMPLE_UNASSALPHA` you would assume it is not going to be returned premultiplied.

> Unassociated alpha channels, on the other hand, can be used to encode a number of independent masks, for example. The original color data is preserved without rounding. Any number of unassociated alpha channels can accompany an image.

This has been [fixed](https://github.com/mapnik/mapnik/blob/48982c061902ac20f185d7f33744010cd8ce6ba8/src/tiff_reader.cpp#L566) in the changes I made associated with image_any. It is now assumed that any image_rgba8 image that is read from the TIFF reader is simply premultiplied. In the event there is an `EXTRASAMPLE_UNSPECIFIED` we throw a [runtime error](https://github.com/mapnik/mapnik/blob/48982c061902ac20f185d7f33744010cd8ce6ba8/src/tiff_reader.cpp#L305)

**Comment by springmeyer** [comment]
> This has been confusing because there is no mention of this in the documentation from what I have seen

@flippmoke Thanks for the details! Want to provide a patch to libtiff documentation after you are back from carving powder turns?
