### ISSUE TITLE
Avoid processing layer datasource if status="off"

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#153]
Mapnik should skip processing the <Datasource /> element for a <Layer /> if the layer status is 'off" or "0".

**Comment by knowname** [comment]
Note that [Nik4](https://github.com/Zverik/Nik4) relies on all layers in the style file to be instanciated, since it is possible to enable or disable the layers and fit the boundingbox according to layers which may not be activated. This doesn't work anymore.
As a solution we could introduce status='initialize' or 'load' in addition to status=off.
