### ISSUE TITLE
GetFeatureInfo() Support

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#2]
The current WMS server implementation does not support GetFeatureInfo().

This will be added as soon as the underlying C++ core and Python bindings allow it.

Depends on ticket:1.

**Comment by erikvullings** [comment]
I'm using node-mapnik (with tilelive) to render a geojson file as tile layer: next, I would like to click on the tile (in leaflet), and use a getFeatureInfo type of method to get information about the selected element. According to this closed issue, this seems to be possible, but I cannot find any documentation about it. Could you please point me in the right direction?

As a reference, I've also found http://gis.stackexchange.com/questions/93221/configuring-mapproxy-mapnik-for-using-getfeatureinfo and http://gis.stackexchange.com/questions/58344/how-to-configure-mapproxy-and-mapnik-for-getfeatureinfo-requests, but alas, without a working solution.

**Comment by springmeyer** [comment]
@erikvullings you have three good options:

  - 1) Send leaflet the geojson directly
  - 2) Render a Utf8Grid tile (see https://www.mapbox.com/blog/how-interactivity-works-utfgrid/ and https://www.mapbox.com/blog/see-how-utfgrid-works-visible-map/ for details)
  - 3) Render a vector tile (see https://www.mapbox.com/developers/vector-tiles/)

1 is the easiest, but might not scale well for large data. 3 is the most flexible and replaces 2.

**Comment by erikvullings** [comment]
@springmeyer Thanks for your good suggestions and links! I take it then that there is no direct implementation of a get feature method in mapnik as this thread suggested?

At 1) Using geojson directly is our default mode in [csWeb](http://tnocs.github.io/csWeb), using leaflet or cesium under the hood, but as you already expected, the files are too big (> 15Mb) to send to the client directly. 

At 3) We can also use vector tiles, but I must say that mapnik renders our traffic data much prettier than we can do with geojson formatting (e.g. different widths for polylines at different resolutions, or having a stroke around a line).

So, the utfgrid seems to be the best way to go. I see you even created a github project for [utf grid writers](https://github.com/springmeyer/utfgrid-example-writers). Do you perhaps have example code for a node-mapnik + utfgrid available, especially in which the map tile and grid are created at the same time :-). We currently use a [wrapper around tilelive](https://github.com/TNOCS/csWeb-tile/blob/master/index.ts), line 164, to render our tiles, and it would be nice if we could integrate the grid creation too.  

Thanks, Erik

**Comment by springmeyer** [comment]
> I take it then that there is no direct implementation of a get feature method in mapnik as this thread suggested?

Incorrect. This ticket was about two things being added: 1) ability in Mapnik core and python bindings to get at feature info via the Python API and 2) The python WMS server implementing GetFeatureInfo according to the WMS spec based on the new Mapnik API.

The python WMS server implementation is now no longer inside Mapnik itself, but lives at https://github.com/mapnik/OGCServer/blob/4e56689164887b6e4352e90c2d961815af6b9002/ogcserver/common.py#L327-L370.

WMS is very rarely used because tiles are higher performance and more widespread. So all you will find in the Mapnik community is experimental WMS servers. So you are really on your own if you want to use WMS. For example https://github.com/mapbox/landspeed.js is a nice implementation of just the `GetMap` part of the spec. Some have added `GetCapabilities` to it like https://github.com/mapbox/landspeed.js/compare/master...mattmakesmaps:annotation. It would not be hard to add `GetFeatureInfo` but I don't think anyone has been interested in this because things like vector tiles are more powerful.

> We can also use vector tiles, but I must say that mapnik renders our traffic data much prettier than we can do with geojson formatting (e.g. different widths for polylines at different resolutions, or having a stroke around a line).

Mapnik can render vector tiles the same way it can render directly from datasources. And web based renderers like Mapbox GL can also render very high quality - really higher quality - in browser from vector tiles at any zoom and even supporting rotation.

> Do you perhaps have example code for a node-mapnik + utfgrid available, especially in which the map tile and grid are created at the same time :-). 

They need to be created at different times via different requests. I think you can figure it out.

**Comment by erikvullings** [comment]
@springmeyer Thanks for your reply and tips. I will give it a go!

**Comment by erikvullings** [comment]
In case other people end up here, I've added a [working example](https://github.com/erikvullings/tilelive-utfgrid/blob/master/examples/tmstyle.js) of an UtfGrid using [tilelive-utfgrid](https://github.com/mojodna/tilelive-utfgrid) that is based on a Mapbox Studio Classic (tm2) project. 

Please note that, at least on Windows, I could not figure out how to embed relative path names in the tm2 ([project.yml](https://github.com/erikvullings/tilelive-utfgrid/blob/master/test/fixtures/road.tm2/project.yml)) and tm2source ([data.yml](https://github.com/erikvullings/tilelive-utfgrid/blob/master/test/fixtures/road.tm2/road.tm2source/data.yml)), which likely means that this examples doesn't work out of the box unless your install folder is ```c:\dev\web\tilelive-utfgrid```.

@springmeyer Should I open an issue for this (no support for relative paths in Mapbox Studio Classic)? Based on your [excellent FOSS4G presentation](https://vimeo.com/106228141), you are probably the best man to ask.
