### ISSUE TITLE
text on multiline in 3.x

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#2412]
Text on multiline in 3.x is rendered only on the first subpath whereas in 2.3.x it works fine.

2.3.x:
![text-multiline-800-800-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/4164608/b40779ae-34f7-11e4-8b78-1a191c5fd16a.png)
3.x:
![text-multiline-800-800-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/4164609/b8f567b4-34f7-11e4-9325-60c57bc925ca.png)

I have added test in this pull request: https://github.com/mapnik/mapnik/pull/2411

**Comment by springmeyer** [comment]
Just happening upon this while fixing #2917. As discussed at https://github.com/mapnik/mapnik-reference/pull/99#issuecomment-108614668 I really don't like this option and it need to be replaced by #1583.

However since we are trying to release 3.0.0 and don't have time to implement #1583 yet I'm giving this option some attention. It seems to me that it only should work against polygons and not lines (or at least I think that is how it worked in 2.3.x) Having to set `largest-bbox-only="false"` feels like a problem.

**Comment by springmeyer** [comment]
restored back compatibility in https://github.com/mapnik/mapnik/commit/5a032ee98be4daa3587110acd7a1aa61aaaffa6b. Now, again, all lines in a multiline get labels by default without needing to set `largest-bbox-only="false"`.
