### ISSUE TITLE
Cannot compile gdal plugin with VC2010

### ISSUE THREAD

**Issue by JamesRamm** [mapnik/mapnik#2565]
The gdal plugin will not compile with VC2010 (and presumably earlier) as it does not support the `rint` function used in gdal_featureset.cpp

**Comment by bartoli** [comment]
gdal_featureset.cpp already includes global.hpp. But **using mapnik::rint;** was removed from that cpp file in https://github.com/mapnik/mapnik/commit/20d06a165164359678ac1f6672c4e6aad034174d, so the standard rint is still searched instead of the mapnik one. Couldn't the **using** be put back, with the same #ifdef conditions as those for rint() redefinition?

**Comment by lightmare** [comment]
VC2010 can't even C++11, closing.
