### ISSUE TITLE
Better bbox reporting

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2618]
We should implement @brandonreavis's suggestions at:
https://github.com/mapbox/mapnik-omnivore/issues/43#issuecomment-65298961

[mapnik_projection.cpp](https://github.com/mapnik/node-mapnik/blob/cc66e715abc30f82d256595f89d2072e7193549d/src/mapnik_projection.cpp#L105-L116)
```c++
double minx = a->Get(0)->NumberValue();
double miny = a->Get(1)->NumberValue();
double maxx = a->Get(2)->NumberValue();
double maxy = a->Get(3)->NumberValue();
p->projection_->forward(minx,miny);
p->projection_->forward(maxx,maxy);
Local<Array> arr = NanNew<Array>(4);
arr->Set(0, NanNew(minx));
arr->Set(1, NanNew(miny));
arr->Set(2, NanNew(maxx));
arr->Set(3, NanNew(maxy));
NanReturnValue(arr);
```
should become something like this:
```c++
double ulx, ulx, urx, ury, lrx, lry, llx, lly;
ulx = llx = a->Get(0)->NumberValue();
lry = lly = a->Get(1)->NumberValue();
lrx = urx = a->Get(2)->NumberValue();
uly = ury = a->Get(3)->NumberValue();
p->projection_->forward(ulx,uly);
p->projection_->forward(urx,ury);
p->projection_->forward(lrx,lry);
p->projection_->forward(llx,lly);
Local<Array> arr = NanNew<Array>(4);
arr->Set(0, NanNew(ulx<llx ? ulx : llx));
arr->Set(1, NanNew(lry<lly ? lry : lly));
arr->Set(2, NanNew(urx>lrx ? urx : lrx));
arr->Set(3, NanNew(ury>uly ? ury : uly));
NanReturnValue(arr);
```

**Comment by flippmoke** [comment]
@springmeyer just to be clear on the problem here, I wanted to draw what the current code does, and then consider what we should do going forward.

![bbox_issue](https://cloud.githubusercontent.com/assets/1794907/7656779/67d89344-faf2-11e4-9284-d32fc1becb0d.png)

If you reprojected `epsg:4326` to `epsg:3857` as a box in the northern hemisphere you might get a resulting box like the dashed blue area shown. The red points are the points we use from a currently transformed bounding box and the green is the new bounding box we form. 

Our current implementation is bad, so we should switch to what he is suggesting, however, this MIGHT also be confusing to some people because you have the possibility to include data that you didn't expect to include in the first place with bounding boxes like this. 

The fool proof solution would be track all 4 corners of a bounding box always, but this would complicate so much.

/cc @artemp

**Comment by flippmoke** [comment]
Implemented fix in https://github.com/mapnik/mapnik/commit/90de0d65cba17cfdb222c126b1279fbdb1d56f38
