### ISSUE TITLE
mapnik.Map.layers only returns active layers in python 3.x

### ISSUE THREAD

**Issue by JamesRamm** [mapnik/mapnik#2646]
I am noticing that the `layers` property of the `Map` object in the 3.x python bindings only returns layers that are active. In 2.2 it returned all layers.

Is this intentional, and if so, is there another way to traverse all layers in 3.x?

**Comment by springmeyer** [comment]
I'm not seeing how that would be possible in the code. This is because `map.layers` [here](https://github.com/mapnik/mapnik/blob/39d8d653432190c2803a4221a525f777e612a5ca/bindings/python/mapnik_map.cpp#L486-L487) uses `layers_nonconst` [here](https://github.com/mapnik/mapnik/blob/39d8d653432190c2803a4221a525f777e612a5ca/bindings/python/mapnik_map.cpp#L54) which hits [here](https://github.com/mapnik/mapnik/blob/39d8d653432190c2803a4221a525f777e612a5ca/src/map.cpp#L358-L361).

So yeah, this has not changed and I would not expect the behavior you are describing. Maybe something else is going on?

**Comment by JamesRamm** [comment]
probably something else. Hard to know what is happening.

Basically I have an xml file with 30 layers. All but two are switched off.
The following will return `2`:

    import mapnik
    xml = "C:/temp/stylesheet.xml"

    map_ = mapnik.Map(256, 256)
    mapnik.load_map(map_, xml)
    print len(map_.layers)

**Comment by springmeyer** [comment]
aha. yes, the above is expected behavior now in 3.x in that layers disabled in XML are not parsed now.

**Comment by JamesRamm** [comment]
ah.
So does this mean you can not iterate all layers of the `Map` object (via python) and set their `active` state anymore?

Is there a way around it, other than:

- Maintain a seperate object representing the xml file (with lxml or whatever)
- Use that to switch layers on/off, which means you would have to save the xml file to disk with each change and reload it to a mapnik `Map`...

**Comment by artemp** [comment]
@springmeyer - this looks like regression in 3.x.  We need to implement 'lazy' parsing for 'disabled' layers or introduce another option to control parsing.

**Comment by springmeyer** [comment]
@JamesRamm you can keep `status=on` in your XML, load the map, and then toggle as you like in python on or off. Does that work?

This behavior is not a regression in the sense that it was an intentional change that was long requested (https://github.com/mapnik/mapnik/commit/e26570dfdb9e2c98211e793138869b896d8f05d9) - the goal being to actually have `status=off` in XML mean to ignore the layers fully.

**Comment by JamesRamm** [comment]
Yes, it could be a work around to keep the status on and then turn off the layers immeadiately in python. 

The motivation behind this is to present the map and all layers in a simple desktop UI for users to quickly create a map of our data (flood data). Most layers are initially turned off to keep the UI responsive when panning/zooming and start up very prompt and user can then turn on layers as desired for the final image.

So in the context of simple GUI's such as this, it is very useful to be able to get hold of all layers in the map...

**Comment by springmeyer** [comment]
> So in the context of simple GUI's such as this, it is very useful to be able to get hold of all layers in the map...

Right, so just disable the layers before rendering. Also, overall I don't think you should depend on Mapnik XML as a project file - better to create an abstraction on top of Mapnik XML and then generate XML based on your specific needs.

**Comment by springmeyer** [comment]
If there are remaining things to discuss let's do it over at https://github.com/mapnik/python-mapnik now that the bindings are standalone (#2773)
