### ISSUE TITLE
PostgreSQL "raw" connection string

### ISSUE THREAD

**Issue by slaskis** [mapnik/mapnik#2741]
I tried to use a postgis datasource which is hosted on Heroku Postgres, but I'm unable to connect to the server because it [requires `sslmode=require`](https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku#ssl) to connect from outside of heroku, which seems reasonable in most occasions but restrictive in this particular case. 

Unfortunately when I took a look at the postgis connection code in mapnik I couldn't find a way to pass any other parameters into the connection string ([the code I looked at](https://github.com/mapnik/mapnik/blob/master/plugins/input/postgis/connection_manager.hpp#L80)).  But maybe there is a way to use a "raw" postgres connection string that I have missed? 

This would be great to be able to connect to the "source" directly with TileMill as well, which also now fails to connect to the heroku postgres server.

**Comment by springmeyer** [comment]
the node-mapnik binaries used inside TileMill intentionally do not ship with ssl support because I disabled openssl in the libpq they are built against. I did this because I did not want to have to depend on openssl.

So, I think the ss requirement to connect is good but it is not going to work unless you source compile your own mapnik + node-mapnik (trigger this with `npm install --build-from-source=mapnik` when building TileMill).

**Comment by springmeyer** [comment]
see also https://gist.github.com/springmeyer/6035044

**Comment by slaskis** [comment]
Aha, so it isn't because of the lack of full connection string. But that's great news. 
Thanks for the quick reply!

**Comment by springmeyer** [comment]
> so it isn't because of the lack of full connection string

Well, it still might be :) Just saying that I'm sure the node-mapnik binaries are the first blocker.
