### ISSUE TITLE
Split up src/renderer_common/process_group_symbolizer.cpp

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2775]
It never finishes compiling on OS X + coverage and needs to be broken down to reduce memory usage: https://travis-ci.org/mapnik/mapnik/jobs/59836815#L835

**Comment by springmeyer** [comment]
Next action: after https://github.com/mapnik/mapnik/commit/c64dc3672a2bc8def5ddcf1c5d3fc612f63c46ab, try to move vertex_converters to cpp.

**Comment by flippmoke** [comment]
Reviewing this again, I feel like this can wait till after 3.0.0 release. Thoughts @artemp ?

**Comment by flippmoke** [comment]
Talked to @artemp about this and we decide to remove this from required for 3.0.0 release for now.

**Comment by lightmare** [comment]
I'm trying to split this monster, as it's one of the four sore thumbs. Its extreme compilation times and memory requirements come from `render_markers_symbolizer`, but I'm not touching that just yet. I started with something simpler: [render_group_symbolizer](https://github.com/mapnik/mapnik/blob/5471f519cd050e43e2fe58cf6c1fac1966dd7a2f/include/mapnik/renderer_common/process_group_symbolizer.hpp#L240)

```c++
template <typename F>
void render_group_symbolizer(group_symbolizer const& sym,
                             feature_impl & feature,
                             attributes const& vars,
                             proj_transform const& prj_trans,
                             box2d<double> const& clipping_extent,
                             renderer_common & common,
                             F render_thunks)
```

'Tis a pretty long function, and the only templated argument, `F render_thunks`, is only used in a loop at the very end. Moreover, its invocations from [agg](https://github.com/mapnik/mapnik/blob/5471f519cd050e43e2fe58cf6c1fac1966dd7a2f/src/agg/process_group_symbolizer.cpp#L157), cairo and grid renderers are nearly identical:

```c++
    render_group_symbolizer(
        sym, feature, common_.vars_, prj_trans, clipping_extent(common_), common_,
        [&](render_thunk_list const& thunks, pixel_position const& render_offset)
        {
            thunk_renderer/* renderer-dependent stuff */ ren(*this, ...);
            for (render_thunk_ptr const& thunk : thunks)
            {
                util::apply_visitor(ren, *thunk);
            }
        });
```

Because [lambda expression constructs an ... object of unique ... type](http://en.cppreference.com/w/cpp/language/lambda), each of agg, cairo and grid will instantiate their own `render_group_symbolizer`. I think this yearns for good old virtual functions. Here's what I did:

```c++
struct thunk_renderer_base
{
    pixel_position offset_; // this is set by render_group_symbolizer before visitation

    virtual void operator()(raster_marker_render_thunk const& thunk);
    virtual void operator()(vector_marker_render_thunk const& thunk);
    virtual void operator()(text_render_thunk const& thunk);
};
```

Moved `render_group_symbolizer` to a separate .cpp file, made it non-template taking `thunk_renderer_base & render_thunks`. The loop with `apply_visitor` went there as well. In `src/{agg,cairo,grid}/process_group_symbolizer.cpp`, I derived their `thunk_renderer`s from this base and used those instead of lambdas:

```c++
    thunk_renderer/* renderer-dependent stuff */ ren(*this, ...);
    render_group_symbolizer(
        sym, feature, common_.vars_, prj_trans, clipping_extent(common_), common_,
        ren);
```

Before the change, each of `src/{agg,cairo,grid}/process_group_symbolizer.cpp` took ~15s to compile for me, 45s total. After the change it's ~5+2+8+11s (the fourth is the new source), 26s total.

What do you think? Is this a good approach? Moving such big functions that don't need to be templates out of headers can speed things up.

**Comment by lightmare** [comment]
@springmeyer This can be closed, it's been split into `src/renderer_common/render_group_symbolizer.cpp` and `src/renderer_common/render_thunk_extractor.cpp` (and most importantly the big template `render_markers_symbolizer` is not there anymore).

The remaining *big* source is `src/renderer_common/render_markers_symbolizer.cpp`. It currently uses `render_marker_symbolizer_visitor` and its inner dispatchers with just one set of template parameters, so these (or even individual function-call operator overloads) could be explicitly instantiated in separate sources, but I'm going to revisit that later, now I'd like to do other stuff :wink:

**Comment by springmeyer** [comment]
> could be explicitly instantiated in separate sources, but I'm going to revisit that later, now I'd like to do other stuff 

:+1: thanks, sounds good to revisit with fresh eyes later.
