### ISSUE TITLE
Missing points in 3.0.0-rc2

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2863]
This is https://github.com/gravitystorm/openstreetmap-carto/issues/1579#issuecomment-105066638 reduced into a smaller testcase

Using the https://github.com/pnorman/openstreetmap-carto/tree/viewpoint_testcase stylesheet, the `view_point.p.16.png` symbol is rendered with Mapnik 2.2.0 but not 3.0.0-rc2

The Kosmtik instance running on port 6789 is using Mapnik 3.0.0-rc2, and port 6788 is Mapnik 2.2.0.

![image](https://cloud.githubusercontent.com/assets/1190866/7790044/f210e864-022b-11e5-8731-da8e98d85cd8.png)

**Comment by springmeyer** [comment]
thanks for reporting. for reference the ideal testcase is one that only uses Mapnik XML so it can be easily converted to a regression testcase in the visual tests: https://github.com/mapnik/mapnik/wiki/A-perfect-testcase

also. I'm on vacation next week so expect me to followup on this or other reports the first week in June.

**Comment by springmeyer** [comment]
Fixed in dcfa0b6. What I found is that Mapnik 2.x supports `point-placement:interior;` one point geometries. This is a bit odd because `interior` placement is only meaningful against polygons, which is why it was natural to start skipping placement in this case. However for back compatibility it is important to keep support for `point-placement:interior;` and the way we did this before and do now is to dispatch to the `centroid` algorithm which itself just takes the actual point location as the centroid. As part of this I fixed a related bug whereby when no placement is attempted for a given geometry type previously (in 3.x) we'd place it as 0,0. This is now fixed and we skip placement overall for geometry types that are not supported (like lines).
