### ISSUE TITLE
load_map is slower with Mapnik 3

### ISSUE THREAD

**Issue by olt** [mapnik/mapnik#2868]
My first tests with Mapnik 3.0.0-rc2 shows that loading XML styles is now much slower then with 2.2.

With Mapnik 2.2 loading a complex style takes about 500ms the first time and around 350ms for all subsequent loads (connection caching?).
With Mapnik 3 loading the same style takes about 1000ms for the first and all subsequent loads.

It looks like it's the initializing of the PostGIS datasources. The XML parsing itself is faster (200ms vs 90ms) if I remove the datasources from the Layers. 

All datasources look like:

    <Datasource>
      <Parameter name="geometry_field">way</Parameter>
      <Parameter name="dbname">gis</Parameter>
      <Parameter name="extent">-20037508,-20037508,20037508,20037508</Parameter>
      <Parameter name="table">(SELECT way, type FROM osm) AS foo</Parameter>
      <Parameter name="type">postgis</Parameter>
    </Datasource>

Is there any known regression for PostGIS datasources?

**Comment by flippmoke** [comment]
It is quite possible that has to do with us correcting geometries prior to processing them in 3.0.0-rc2. In our WKB processor we now do a geometry correction. 
https://github.com/mapnik/mapnik/blob/master/src/wkb.cpp#L414

This was done in https://github.com/mapnik/mapnik/issues/2834

due to:

https://github.com/mapnik/mapnik/issues/2793

If you wanted to build a benchmark for this it would be great to see some definite numbers. See the example benchmarks we have in the repo.

**Comment by olt** [comment]
Thanks for the hints.
The numbers above are from ``mapnik::load_map`` only, the rendering times are nearly identical in my test case.

**Comment by olt** [comment]
Ok, found the issue. 
I get the same times with Mapnik 3.0.0-r2 if I add the `srid` to the datasource. Mapnik 3 makes a query for each datasource to `geomerty_columns` and this takes a few ms on my system. This adds up with ~80 layers. Mapnik 2.2 somehow did not need the srid.
