### ISSUE TITLE
SVG <rect> - large out-of-range "rx" / "ry"

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#2991]
Inscape can output rounded rectangles with invalid rx/ry.

To comply to spec out-range values need to be clipped to `0.5 * width` or `0.5 * height` respectfully.
http://www.w3.org/TR/SVGTiny12/shapes.html#RectElement

```
<rect
	  style="fill:#e6e6e6;fill-opacity:0;stroke:#666666;stroke-width:0;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none"
	  id="rect3036"
	  width="23.077168"
	  height="25.51"
	  x="0"
	  y="0"
	  transform="matrix(96.859343,0,0,96.859343,-34.149654,-300.48966)"
	  rx="545436.62" ry="24.5" />
```

**Comment by artemp** [comment]
fixed in 804115089b1f243fcb5649af94974143ef9d1d43

**Comment by andreasviglakis** [comment]
this came up when i was modifying a highway shield svg so that the shield's text was properly aligned. i would bring each shield into inkscape, resize the document, shift the shield within the new boundaries as necessary, and then create a transparent rectangle that covered the entire document area. after saving and restarting mapbox studio, the shields were simply invisible and there was 500 error message at the bottom of the main studio window. fwiw, i had done the above process 75-100 times before I got this error.

@springmeyer

**Comment by springmeyer** [comment]
thanks @andreasviglakis - am I understanding correctly that you think what you saw is related to inkscape rarely serializing invalid values? And that now that we clamp per @artemp's fix upcoming mapnik should be able to gracefully handle this and still display the SVG? <-- this is my sense after reading this.
