### ISSUE TITLE
Offset artifacts

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#3041]
I have quite a lot of polygons where offsetting produces following artifacts after https://github.com/mapnik/mapnik/pull/2904.

![polygon-offset-1-800-800-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/9466741/4cbadfb4-4b37-11e5-9aad-9dc0e2891b0d.png)

Before https://github.com/mapnik/mapnik/pull/2904:
![polygon-offset-1-800-800-1 0-agg-orig](https://cloud.githubusercontent.com/assets/1950911/9466742/4cbee88e-4b37-11e5-8947-643a9905d185.png)

Complete test is in https://github.com/mapycz/test-data-visual/commit/4a0db3f8b6d4658ee23ea398804a8f208b962f1f.

**Comment by artemp** [comment]
@flippmoke ^

**Comment by talaj** [comment]
It also makes labeling such lines problematic as there are huge angle differences between adjacent characters due to those spikes.

**Comment by flippmoke** [comment]
Nightmare on offset street. This entire algorithm needs to be revisited, however, it would be a heck of a lot easier if it was able to be done in a mapnik::geometry object rather then in the agg vertex format...

**Comment by talaj** [comment]
> it would be a heck of a lot easier if it was able to be done in a mapnik::geometry object rather then in the agg vertex format

And that is problem because all the [vertex converters](https://github.com/mapnik/mapnik/blob/master/include/mapnik/vertex_converters.hpp) operates on the agg vertex format?

**Comment by flippmoke** [comment]
@talaj yes, the other problem is that it needs to be quick and many of the other offset algorithm as very slow, I will probably have to think long and hard about this one.

**Comment by talaj** [comment]
I can see the improvements in visual tests but I moved back to the old proven algorithm. It breaks existing maps and only solutions I see currently are workarounds. I might find some spare time to dive into the offsetting code.

Also I'm not convinced that inversion of offset direction on lines was worth the loss of compatibility.

**Comment by winni159** [comment]
Hi! I'm working on this issue and I have some nice results for the polygon above and the others:
a)
![after-polygon-offset-1-800-800-1 0-agg](https://cloud.githubusercontent.com/assets/3541452/10863030/6006fe64-7fc0-11e5-9be3-62de3e250bf1.png)
b) San Marino before:
![before-polygon-offset-7-400-400-1 0-agg](https://cloud.githubusercontent.com/assets/3541452/10863111/eed42624-7fc2-11e5-9ed3-2b452107ce45.png)
After my changes:
![after-polygon-offset-7-400-400-1 0-agg](https://cloud.githubusercontent.com/assets/3541452/10863114/02947754-7fc3-11e5-8865-e711c69b7ed6.png)
c) And some sharp angles before:
![before-polygon-offset-2-600-600-1 0-agg](https://cloud.githubusercontent.com/assets/3541452/10863119/2b0e8a26-7fc3-11e5-809d-494f34536fbe.png)
After my changes:
![after-polygon-offset-2-600-600-1 0-agg](https://cloud.githubusercontent.com/assets/3541452/10863121/3b837c2c-7fc3-11e5-9a0b-f42e42b1215b.png)

The main problem was in the "displace2" method for offseting sharp angles. Firstly I replaced cutting of hsa and hca values by scaling, which solved the problem with misplaced ofsetted verticies in the polygon on the image c).
Secondly for polygons on images a) and b) I made a little hack. Here is the image for explanation: 
![verticies](https://cloud.githubusercontent.com/assets/3541452/10863375/eb66a904-7fcb-11e5-99ff-8d1a67ec965d.png)
In the first case a) is the vertex "v" displaced to "o" by the "displace2" method and its distance from "v" is offset + h. It cause right distance (offset) between ofsetted and original edges. In the second case b) the vertices "v0" and "v1" (bulge angle) are displaced by the "displace" method which moves them by offset only. Between these verticies "v0" and "v2" lies the vertex "v1" with sharp angle and the "displace2" method moves it by offset + h (to "o1"), where h is relatively high. This situation you can see in the image. This may cause problems ("artifacts") in filtration at the end of algorithm and because of this I made a little hack. If the sum of distances |v0v1| and |v2v1| is less than offset, the vertex "o1" is displaced within a distance of offset. This removes the artifacts in offseting complex polygons or lines.

I tested this solution and some of the visual tests failed, but in my opinion results are visually OK. I'll commit the changes on Monday.
