### ISSUE TITLE
Visual tests 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3049]
I just upgraded: 

```
pixman-0.32.4 ->  pixman-0.32.6
cairo-1.12.16 ->  cairo-1.14.2 
```
and I'm getting

```
Visual rendering: 328 failed / 2230 passed / 0 overwritten / 0 errors
```

All failures are false alarms but raise important issue about visual tests in general: what are we actually testing ?  Pixel-to-pixel comparisons are very fragile and likely to fail when third-party libraries get an update.

I don't like linking each mapnik version to a particular dependency version in order to get tests passed.
Much better solution would be to move all visual tests to unit/functional tests. This would be a lot of work but the end goal of _stable_ tests make it worth the effort.

What do others think?

/cc @springmeyer @talaj @flippmoke @everyone

**Comment by flippmoke** [comment]
Could not agree more! :+1: to more unit tests!

**Comment by talaj** [comment]
Visual tests are more integration tests than unit tests. It's not ideal, but I think there is place for visual tests. Most of the bugs I catch by diffing a real map renders. After each Mapnik/style change I do diff where I can see the impact of the change.

Advantages of visual tests are:
* Can be easily created
* Can be easily visual-checked
* Can be easily updated

Disadvantages:
* Fragile on 3rd party dependencies
* High coupling, low cohesion - low isolation of particular tested feature (it's not unit test)

**Comment by springmeyer** [comment]
All for improving and always thinking about ways to test better. I have some strong opinions here from putting a lot of work into the visual tests to get them where they are and also how they work. 

So in terms of tests failing with different pixman/cairo I think about this differently. They should fail. This is good. I'll explain below.

> All failures are false alarms but raise important issue about visual tests in general: what are we actually testing ? Pixel-to-pixel comparisons are very fragile and likely to fail when third-party libraries get an update.

This is fully by design. We are testing pixels exactly and expecting the pixels are the same across all operating systems. The value of this is that we'll get failures when anything changes in how code might behave differently per OS and we'll get failures the moment any code change that makes the visual result different in any way. I would much much prefer manually triaging visual test failures that are ultimately not perceptibly different than the alternative. The alternative is what we had before: slightly different tolerances per OS and per type of renderer. You needed to update the test fixtures less frequently and less often were those updates needing to make changes that did not visually look different. However underneath that convenience was a total mess. It was often that you'd see "drift". Results could be subtly change over time due to multiple things and only slowly near the failure threshold. Then all of a sudden the test would actually reach the threshold and start failing - potentially due to multiple factors.

So, the express design of the visual tests is to only work with a specific set of dependency versions.  This means that all core devs should use the same dependency versions. I don't have any good ideas at this point about any other ways to avoid this need. In terms of cairo I would have updated the visual tests to target the new cairo already but hit a build problem I've not had time to solve (https://github.com/mapnik/mapnik-packaging/commit/3ab051556e8c8f582d961b69567f55894a7da926).

Overall, I recognize the hassle. But I'm still opinionated on this because I feel that we should be testing and care a lot about the result of mapnik changes to test differences. I'm not sure we benefit much from caring about the impact of different cairo versions on the results. 

I've invested in https://github.com/mapbox/mason and the bootstrap.sh in mapnik core in order to make testing like this more possible (all devs using the same deps versions). See https://github.com/mapnik/mapnik/issues/2662 the background.

> I don't like linking each mapnik version to a particular dependency version in order to get tests passed.

See above. I do like this.

> Much better solution would be to move all visual tests to unit/functional tests.

Yes, let's write more unit/functional tests. But they should complement not replace the existing visual tests.

> This would be a lot of work but the end goal of stable tests make it worth the effort.

Totally.

**Comment by springmeyer** [comment]
cairo upgraded in bootstrap.sh in https://github.com/mapnik/mapnik/commit/49e817fc2eccc55dfc78ecaaf4f55b83935ab5c6 and visual test followup in https://github.com/mapnik/mapnik/commit/64f26284881579829c0615d2b546e9c9f7c0ce61. Visual tests should now all pass for folks like @artemp that have source installed cairo-1.14.x. Those using `bootstrap.sh` will need to remove `./mason_packages` and re-run `source ./bootstrap.sh` to get the new dep versions. The freetype, boost, and icu upgrades appeared to lead to no test differences (yay) except for #3111
