### ISSUE TITLE
Strange artifacts with line-offset and MultiLineString

### ISSUE THREAD

**Issue by ericfischer** [mapnik/mapnik#3070]
Sorry for the Mapbox-centricity of this issue but I think it is a general problem. There are very strange artifacts when drawing MultiLineString features with line-offset.

Make a tileset that combines many lines together into the same feature using moveto, lineto, moveto, lineto, etc. As an example, I used the TIGER 2014 streets for Alameda County, California (uploaded to Mapbox as `enf.4rcqh0k9`) and encoded with tippecanoe:

    cat tl_2014_06001_roads.json | ./tippecanoe -f -X -aco -o multilinestring.mbtiles

Make a style for it like this:

    #multilinestring {
      line-width: 2;
      line-offset: 6;
    }

There are many strange drawing artifacts as shown in this screenshot:

![screen shot 2015-09-14 at 5 00 13 pm](https://cloud.githubusercontent.com/assets/1951835/9864773/45e0faa4-5b02-11e5-9311-21e82de9fa17.png)

Many line segments do not draw at all. Others are drawn but with hooks on the ends, proportional to the size of the line-offset.

cc @flippmoke @springmeyer @danpat

**Comment by talaj** [comment]
https://github.com/mapnik/mapnik/issues/3041 is most likely related.

**Comment by flippmoke** [comment]
So some notes about this image and my understanding of why these issues are occurring:

Our current offset algorithm is based on a streaming geometry structure (basically a list) and is the offset algorithm is typically the last algorithm applied.  This means that we do not have random access to the entire structure. It is this way because of the performance optimizations of this structure prior to rendering as this can be streamed to the different algorithms. 

Because of this when the algorithm starts receiving points it does not know if it is a polygon or line until it reaches the end of processing. Additionally different geometry parts (such as holes) are known parts of the same geometry. 

The offset algorithm initially starts simply to attempt at streaming an offset which is saved to a vector, based on the size of the angle it either makes a curve or sharp turn. As we do not know if it is a line or polygon, we can not easily detect winding order (not do we want to spend the time to determine this). Winding order must be correct prior to passing it into the algorithm otherwise offset would result in different results with different geometries. 

The algorithm for making an offset only knows about the previous point, current point, and the next point. From this an angle is determined and the offset is drawn in a streaming manner. This creates many self intersections with the offset as it is a true offset of the existing path, rather then a buffer operation (which is what many people expect). 

Knowing this we have created a very crude filter that attempts to clean up the "curly features" that are created from the pure offset.

#3041 has a good example of this:

![image](https://cloud.githubusercontent.com/assets/1794907/9879448/0ad987a6-5b8d-11e5-8147-57cb951f98ad.png)

The issue with this filter is that as we make it more strict, it will remove the correct offset line at times. There are many examples of this in the picture you have posted above @ericfischer. 

The curls at the end of the line are most likely due to nearly the same points likely repeated. The offset algorithm thinks this is a small turn, and will make it curve around to meet this point. It would be interesting to see if these curves still exist if you apply simplification prior to the offsets.

**Comment by ericfischer** [comment]
Thanks for the explanation @flippmoke! That clears up most of the mysteries.

These geometries *are* already simplified to the tile resolution, though. Maybe it's a lineto a point and then a moveto just a pixel away to get to the next segment?

**Comment by ericfischer** [comment]
@flippmoke It's still not as tiny as perhaps it could be, but here is [a fairly minimal geometry that exhibits the problem](https://gist.github.com/ericfischer/3f7b5af38c1754416502), even simplified to much coarser than display resolution. I uploaded it to Mapbox not by processing with tippecanoe but through the uploader Mapnik pipeline from GeoJSON as `enf.ve06yldi`.

You can see the hooks well near -122.3000,37.8486:

![screen shot 2015-09-15 at 3 25 08 pm](https://cloud.githubusercontent.com/assets/1951835/9891800/047d30de-5bbe-11e5-8345-74164b21ca17.png)

in this case styled with

    #original {
      line-width: 2;
      line-offset: 12;
    }

**Comment by flippmoke** [comment]
Thanks @ericfischer will try to get to reviewing this soon.

**Comment by flippmoke** [comment]
@ericfischer what version of Studio are you using there?

**Comment by ericfischer** [comment]
This screenshot is from version 0.2.7.

**Comment by flippmoke** [comment]
@ericfischer can you try `0.2.8` -- `0.2.7` uses the old mapnik algorithm before my changes!

**Comment by ericfischer** [comment]
Thanks @flippmoke. This actually looks great in 0.2.8. The only visible hooks are where streets do legitimately make very tight turns.
