### ISSUE TITLE
Build with libxml2

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#3191]
Every time I build the newest Mapnik, I forget to enable the support for libxml2. Is it intention that this dependency is not enabled, if found?

Instead of `./configure` call:
```
python scons/scons.py configure XMLPARSER=libxml2
```

Please just close this issue, if it is not relevant.

**Comment by artemp** [comment]
@der-stefan - default XML parser is `boost::property_tree` so yes, it is intentional (closing)

**Comment by der-stefan** [comment]
Thank you for the explanation, @artemp. Libxml2 is needed for the support of XML entities (see https://github.com/mapnik/mapnik/wiki/ManagingLargeXmlFiles).
Closed.

**Comment by tomhughes** [comment]
I've just been asked to build mapnik 3 with libxml2 as the parser in Fedora for much the same reason (XML entities) so before I go ahead what was the reason for the switch and is there any good reason why I shouldn't use libxml2 still?

**Comment by springmeyer** [comment]
The reason for the switch was:

- rapidxml (boost ptree) is faster
- rapidxml requires no external deps
- libxml2 is known to be problematic if it is not built with multithreading support (countless bug reports of hangs from Python programs)
- the only value add of libxml2 above ptree is its support for entities. however these are rarely used and easy avoided by preprocessing a style sheet with xmllint before passing to Mapnik.

**Comment by der-stefan** [comment]
Ok, this is new to me. We use entities since reading the wiki article https://github.com/mapnik/mapnik/wiki/ManagingLargeXmlFiles. So this procedure is out of date?

**Comment by talaj** [comment]
> * the only value add of libxml2 above ptree is its support for entities. however these are rarely used and easy avoided by preprocessing a style sheet with xmllint before passing to Mapnik. 

I think it's not that simple. If I have a set of very complex styles in XML, entities and `XInclude` are basic ways how to prevent code duplication and how to turn magic numbers into named constants. Preprocessing by `xmllint` is complication when I'm using Mapnik in several tools like batch rendering, dynamic rendering and style-debugging tools simultaneously. Just passing styles to Mapnik is simple and less error-prone.

Using things like CartoCSS is not suitable solution for me because:

* It's just another dependency.
* I would have to rewrite all the complex styles and virtually throw the git history.
* I would have to convince cartographers that there is some value in such transition.
* Cartographers would have to learn it.
