### ISSUE TITLE
More coverage for SVG's

### ISSUE THREAD

**Issue by jakepruitt** [mapnik/mapnik#3229]
In order to get more coverage for SVG parsing code, and more conformance to SVG 1.1 standard, there should be better tests around our SVG parser and renderer.

All of the svg [source](https://github.com/mapnik/mapnik/tree/master/src/svg) code in mapnik-core is in `src/svg` , the [headers](https://github.com/mapnik/mapnik/tree/master/include/mapnik/svg) are at `include/mapnik/svg`, and [unit tests](https://github.com/mapnik/mapnik/tree/master/test/unit/svg) for that code are in `test/unit/svg`.

**Visual tests**

For visual tests, it would be good to create simple styles with just one marker in the middle, and have a new style for every different SVG we want to try out. [This style](https://github.com/mapnik/test-data-visual/blob/master/styles/marker-svg-empty-g-element.xml) is a good example of an xml style that can be modified to use a different svg. I would start by copying this file, and renaming it:

```
/test/data-visual/styles/marker-svg-{name-of-test}.xml
```

There will be corresponding output images with the format

```
/test/data-visual/images/marker-svg-{name-of-test}-reference.[png|svg]`
```

By the looks of things, there are not very many tests here that are focused on testing the rendering of SVG's, so it's ripe for exploration! Adding more tests with our existing SVG's, and finding more SVG's from places like [W3G](http://www.w3.org/Graphics/SVG/Test/20110816/) would be really useful. See https://github.com/mapnik/mapnik/issues/3005 for inspiration on different SVG properties to test. We should be looking for the output images to always look like the output we would expect from another SVG renderer.

**Unit tests**

Unit tests should be updated to get 100% coverage on all SVG source files (in `/src/svg`). Here are some svg files with bad coverage (taken from https://coveralls.io/builds/4700614):
- `include/mapnik/svg/svg_path_adapter.hpp`  80.87%
- `include/mapnik/svg/svg_transform_grammar.hpp` 78%
- `src/svg/output/svg_generator.cpp` 73%
- `src/svg/output/svg_output_attributes.cpp` 29%

Other files here may have good coverage because of visual tests, but the actual logic may not be carefully tested. Since the [last run](https://github.com/mapnik/mapnik/issues/3005) at logic testing of svg parsing, we've added more support for more SVG properties. There should be unit tests in `/test/unit/svg` that specifically cover the parsing of these properties:
- [ ] stroke-dash-array
- [ ] stroke-dashoffset
- [ ] other stroke-\* properties (see http://www.w3.org/TR/SVG/painting.html#StrokeProperties)
- [ ] any other path properties (see http://www.w3.org/TR/SVG/paths.html)

Feel free to add more properties to the above list as we go. cc/ @mapsam, @artemp @flippmoke @springmeyer

**Comment by mapsam** [comment]
Added a [new SVG](https://github.com/mapnik/test-data/blob/svg-visual/svg/shield-multiple-command-parts.svg) to `mapnik/test-data` from #3225 in order to cover any SVGs with multiple command parts in `path d` attributes. Reference images look good over at [`mapnik/test-data-visual`](https://github.com/mapnik/test-data-visual/tree/svg-visual/).

**Comment by springmeyer** [comment]
/cc @artemp who is working on improving the SVG parser. I've added this to the v3.0.16 milestone.

Things changed since this ticket was created:

  - We are now tracking coverage at https://codecov.io/gh/mapnik/mapnik/tree/master/src/svg
  - There is now a wiki page tracking what is supported: https://github.com/mapnik/mapnik/wiki/SVG-support
  - There is work underway to make the parser optionally more strict and support missing features (https://github.com/mapnik/mapnik/tree/svg-strict-parsing)

Things that have not changed:

  - We still need greater SVG test coverage in the unit tests (currently ~ 91 % for https://codecov.io/gh/mapnik/mapnik/src/master/src/svg/svg_parser.cpp, would be great to be near 100%)

**Comment by artemp** [comment]
Closing and moving to https://github.com/mapnik/mapnik/issues/3788
