### ISSUE TITLE
Compiling render_markers_symbolizer.cpp needs unreasonable amounts of memory

### ISSUE THREAD

**Issue by tomhughes** [mapnik/mapnik#3327]
I was hopeful that #3265 would fix this, but now that 3.0.10 has been released it seems like things actually worse than in 3.0.9 :cry: 

With 3.0.9 I was able to build on all three of the Fedora primary architectures, but I needed to disable debug generation for 32 bit x86 and ARM or it would run out of memory.

With 3.0.10 not only do I need debug disabled still, but the ARM won't compile even with debug disabled without running out of memory compiling `src/renderer_common/render_markers_symbolizer.cpp`.

An example log of a failing ARM build is https://kojipkgs.fedoraproject.org//work/tasks/9176/13149176/build.log.

**Comment by lightmare** [comment]
You're right, it has grown. Before the refactoring, there were 4 files that required 3.9+GB to compile with gcc 4.8. Afterwards only `src/renderer_common/render_markers_symbolizer.cpp` needed 4.2+GB -- that was good enough for me, as I could finally use JOBS=2; and I switch to building with clang by default, it only needs ~2GB to compile that.

I've just checked with gcc again and it went above 4.8GB, that's bad. It might be changes in variant, or boost/other libs I upgraded since then.

**Comment by tomhughes** [comment]
The problem is that a 32 bit machine has an inherent limit of 4Gb for a single process regardless of how much memory there is in the machine, so a compile that needs that much memory is going to be impossible on any 32 bit machine...

**Comment by artemp** [comment]
I just checked compile times for 3.0.9 and 3.0.10

##### v3.0.9

Total build time: 628.225099 seconds
Total SConscript file execution time: 0.697090 seconds
Total SCons execution time: 5.218378 seconds
Total command execution time: 622.309631 seconds

real	10m28.517s
user	73m18.336s
sys	1m36.722s

##### 3.0.10

Total build time: 559.878520 seconds
Total SConscript file execution time: 0.707139 seconds
Total SCons execution time: 4.951279 seconds
Total command execution time: 554.220102 seconds

real	9m20.166s
user	64m44.853s
sys	1m36.995s

They look good (as in better) in 3.0.10 but  `src/renderer_common/render_markers_symbolizer.cpp` memory requirement is breaking 32-bit builds now which is bad.

Taking `render_marker_symbolizer_visitor` out of `render_markers_symbolizer.cpp` and perhaps splitting `void operator() (marker_svg const& mark) const` and ` void operator() (marker_rgba8 const& mark) const` into separate *.cpp might help.

@lightmare - have you got any better ideas ?
/cc @tomhughes

**Comment by lightmare** [comment]
During the weekend I tried attacking it from the bottom, `vertex_converters` and such, so far with no visible improvements.

Taking the visitor operators out is probably the way to go. I think taking out the visitor itself isn't going to help, as it's basically the only code in there; but since I previously hard-coded its template parameters, operators could delegate to free functions defined in separate sources.

**Comment by lightmare** [comment]
Progress update: splitting operators didn't help much. I moved only the converter setup and `apply_markers_multi` call into separate `render_marker_svg.cpp` and `render_marker_rgba.cpp`.
 - before
   - render_markers_symbolizer.cpp 127s 4840MB
 - after
   - render_markers_symbolizer.cpp 10.5s 890MB
   - render_marker_svg.cpp 121s 4788MB
   - render_marker_rgba.cpp 121s 4787MB

Interesting, huh? The `operator()(marker_svg)` and `operator()(marker_rgba8)` overloads use different `rasterizer_dispatch` type, and thus different specializations of `apply_markers_multi` (the function template responsible for these huge memory needs). The fact that splitting them didn't cut memory usage in half was to be expected -- those operator overloads are separate functions, the compiler can work on them separately, doesn't need to hold both `apply_markers_multi` specializations in memory. What's more interesting is that splitting them didn't halve the compile time of each -- when they're in different sources, all the work on `apply_markers_multi` template is done twice, while before the compiler apparently only did that once. And that's the most surprising for me -- I thought because they're different specializations, it'd need to do most of the work twice, anyway, even when they were in the same souce.

**Comment by artemp** [comment]
@lightmare - Oh no... thanks for trying ! 

`apply_markers_multi` is the beast and needs some magic to be tamed.

**Comment by lightmare** [comment]
For the record, I'm now looking into `markers_placement_finder`. When I inadvertently removed move constructors on placement-implementation classes, I got the usual shower of template errors, but one caught my interest:
```c++
variant(variant<Types...>&& old) noexcept(std::is_nothrow_move_constructible<std::tuple<Types...>>::value)
                                               ^
note: in instantiation of exception specification for 'variant' requested here
class variant : public mapbox::util::variant<Types...>
```

The exception specification is correct, it's just that I hadn't realized how big it can get when I wrote it. In `markers_placement_finder`, there are five alternatives in `Types : markers_point_placement<Locator, Detector>, markers_line_placement<Locator, Detector>, ...`, and `Locator` is a composition of vertex converters, which isn't short. One of the error lines was 8k characters. This might be partially responsible for increased memory needs.

Anyway, I was looking at `markers_placement_finder` during the previous symbolizer refactoring, already. I'll try replacing the variant with raw union... yes sounds hacky, but 1) the thing is a strategy, variant is not the most elegant way to implement that, either; 2) I'm really curious whether that will help :ram:

**Comment by lightmare** [comment]
@artemp - I rewrote `markers_placement_finder` and it look promising. Clang went down from 2G/91s to 1G/65s and GCC from 4.8G/121s to 2.1G/95s on the split files; now I'm putting them back together, as the split itself didn't help at all, quite the contrary, I think it'll be better.

**Comment by artemp** [comment]
@lightmare - great! I was trying couple things too and at least locally I get better compile times + less memory usage. 
#### 3.0.10
```
Total build time: 643.643920 seconds
Total SConscript file execution time: 0.725485 seconds
Total SCons execution time: 6.083753 seconds
Total command execution time: 636.834682 seconds

real	10m43.962s
user	70m34.701s
sys	1m55.524s
```
#### master
```
Total build time: 535.807735 seconds
Total SConscript file execution time: 0.710405 seconds
Total SCons execution time: 5.025317 seconds
Total command execution time: 530.072013 seconds

real	8m56.114s
user	62m11.038s
sys	1m38.517s
```

**Comment by artemp** [comment]
@lightmare - I'm looking forward to trying out new `markers_placement_finder` implementation ^ 
Can you make a PR ?

**Comment by lightmare** [comment]
Closing, Fedora builds seem to be fine again. http://koji.fedoraproject.org/koji/packageinfo?packageID=6670
