### ISSUE TITLE
180 meridian labels

### ISSUE THREAD

**Issue by coprogrammer** [mapnik/mapnik#3332]
Hello! There is a little problem with labels near 180 meridian. Looks like Mapnik sees two geometries and makes two labels for Russian Federation.
![osm](https://cloud.githubusercontent.com/assets/17545445/13393482/2d8fac3e-defb-11e5-91ca-cee38a19f022.png)
![osm1](https://cloud.githubusercontent.com/assets/17545445/13393501/455ac2d6-defb-11e5-9bb1-81f7ac4127f5.png)

**Comment by tomhughes** [comment]
It's likely that this is an issue with the data and/or the stylesheet rather than an issue with mapnik itself.

For the record that island is a multipolygon (http://www.openstreetmap.org/relation/5576598) with separate polygons for the pieces on each side of the 180 degree line, but there are also various coastline elements involved which are also split across the meridian.

In general things spanning the meridian will probably be split in two in the OSM database because we don't allow things beyond -180/180 and many things have problems with wrapping if you have things which cross the line and wrap around.
