### ISSUE TITLE
Breaking change: no unquoted strings

### ISSUE THREAD

**Issue by jchamberlain** [mapnik/mapnik#3387]
3.0.10 has removed support for unquoted strings in filter expressions (d01da6f86acb0f14de44ac42ed21a073fe5e84cf). We've somewhat accidentally been using them, and were surprised that our maps broke on upgrading, especially since there's no mention of it in the changelog.

If you could update the changelog to reflect that I'd appreciate it, and it might save someone else my surprise. Thanks!

**Comment by mapsam** [comment]
Hey @jchamberlain thanks for bringing this up! The removed support was intentional but we never recorded it in the changelog, and are now seeing this come up elsewhere so we brought the functionality back in for the time being via #3389 and #3390. We are planning on tagging this at `3.0.11`, but the unquoted strings in filter expressions will likely be removed soon.

**Comment by jchamberlain** [comment]
That makes sense. We've already updated our code to quote strings properly--a pretty quick fix--I just wanted to make sure this was publicly recorded somewhere.

**Comment by mapsam** [comment]
Excellent, glad to hear you got a fix in place. We'll make sure the changelog is updated appropriately the next time around!
