### ISSUE TITLE
highway tag for elements of highway relation not honoured

### ISSUE THREAD

**Issue by mfrasca** [mapnik/mapnik#3458]
I have a right-angled triangular open area, which is bordered on two sides (the two legs or catheti) by a road, the hypotenuse I would not consider a road, but it makes little difference here.
I define the two road segments as highway:residential and give the multipolygon the same tag. the hypotenuse is untagged.
the rendering I get is this (highway tag in the border segments are not honoured - no thickness)
![current](https://cloud.githubusercontent.com/assets/122869/16361199/47c808de-3b77-11e6-800f-70fac7baba99.png)
I really expect this rendering, where the legs are represented as roads, and the residential area extends it:
![expected](https://cloud.githubusercontent.com/assets/122869/16361238/dd96273c-3b78-11e6-9a8b-fa8fc7620739.png)
on the other hand, if the tag on the relation is different from the tag on the elements, all are honoured:
![213731](https://cloud.githubusercontent.com/assets/122869/16361257/33416fa2-3b79-11e6-88b7-a8a90ff90e21.png)

**Comment by der-stefan** [comment]
This is no problem of Mapnik, but of your style file.

**Comment by mfrasca** [comment]
if I understand you correctly, @der-stefan, you suggest I report this to OSM, not to mapnik, and that OSM correct the relevant style file.

**Comment by der-stefan** [comment]
Yes, please. I thought it was your own renderer, but anyway, it's an issue with the style. So yes, here: https://github.com/gravitystorm/openstreetmap-carto
(This is the official style, don't mind that it is not in the openstreetmap repo.)

**Comment by mboeringa** [comment]
@mfrasca  and @der-stefan:

I don't think this is necessarily a style issue: this is an ambiguous situation that could be tagged differently to avoid this:

Instead of re-using the road segments in a multipolygon to create the triangular area, you should only re-use the nodes.

E.g. by first drawing the triangular area as a closed way and setting explicit area=yes, and then by drawing new line elements for the roads and merging the nodes of the new features with the existing nodes of the closed way.

This way, your road line elements and area also become distinct osm objects, where only the nodes are re-used, and not the line elements.

This is different from the current tagging (AFAIU), and would most likely avoid this issue, as there is no multipolygon re-using the line elements, while still allowing the efficiency of single merged nodes.
