### ISSUE TITLE
Wrong German translation of beauty shop

### ISSUE THREAD

**Issue by scit2010** [mapnik/mapnik#3467]
Given a beauty shop with
shop=beauty, beauty=nails.
The OSM standard renderer shows the node as "Parfümerie" (perfumery), while "Nagelstudio" (nail salon) is the right term here.

**Comment by tomhughes** [comment]
Firstly, this repo is for the mapnik engine - the stylesheet used on the OSM site is at https://github.com/gravitystorm/openstreetmap-carto/ so that is where issues with it should be reported.

That said I don't think you're talking about the rendering anyway, as we don't render the names of types of shops, and we certainly don't do any translations of them.

I think you need to explain exactly where this incorrect translation is appearing before we can help.
