### ISSUE TITLE
Query with character @ doesn't render

### ISSUE THREAD

**Issue by alculquicondor** [mapnik/mapnik#3603]
I have this query:
```
<Parameter name="table">(SELECT * FROM dataset WHERE added_by = 'somebody@example.com') AS suquery</Parameter> 
```
which doesn't render.
AFAIK, @ is not a character that needs to be escaped in XML.

I'm running mapnik 3.0.12. Is this a known issue? If so, can you recommend a workaround?

**Comment by springmeyer** [comment]
Can you enable postgres logging, and intercept the query mapnik is passing? Then share that?

**Comment by alculquicondor** [comment]
on it

**Comment by alculquicondor** [comment]
```
LOG:  statement: SET DEFAULT_TRANSACTION_READ_ONLY = TRUE; SET CLIENT_MIN_MESSAGES = WARNING;
LOG:  statement: SELECT f_geometry_column, srid FROM geometry_columns WHERE f_table_name='dataset_289' AND f_geometry_column='wkb_geometry'
LOG:  statement: SELECT * FROM (SELECT * FROM dataset_289 WHERE added_by = 'aldonull.com') AS suquery LIMIT 0
LOG:  statement: SET DEFAULT_TRANSACTION_READ_ONLY = TRUE; SET CLIENT_MIN_MESSAGES = WARNING;
LOG:  statement: SELECT ST_XMin(ext),ST_YMin(ext),ST_XMax(ext),ST_YMax(ext) FROM (SELECT ST_Extent(wkb_geometry) as ext from dataset_289) as tmp
LOG:  execute <unnamed>: SELECT ST_AsBinary("wkb_geometry") AS geom FROM (SELECT * FROM dataset WHERE added_by = 'somebodynull.com') AS suquery WHERE "wkb_geometry" && ST_SetSRID('BOX3D(-91.4062499999998 -23.24134610238655,-66.09374999999974 1.406108835434752)'::box3d, 4326
```

**Comment by alculquicondor** [comment]
Just for reference, I compiled mapnik with default configuration:
```
    python scons/scons.py configure && python scons/scons.py install
```
So I guess the parser is rapidxml

**Comment by talaj** [comment]
`@` denotes [render-time variables](https://github.com/mapnik/mapnik/issues/2553). I don't know how to escape them.

**Comment by alculquicondor** [comment]
Anyone else please?

**Comment by lightmare** [comment]
This is a regression due to e300a41d. Proper fix will probably require some discussion about the grammar, possible solutions include taking `@` literally when it's preceded by a non-space, or a word character, or some escape character.

The quickest fix for you will be splitting the string after the `@` so it won't match the regex `@\w+`, i.e.
```sql
 WHERE added_by = 'somebody@' || 'example.com'
```

**Comment by lightmare** [comment]
Given that the long-supported syntax for injecting a value from mapnik into the SQL is `!something!`, it would make sense to not introduce `@` as another special leading character, but simply allow it inside, i.e. `!@uservar!`.

But I'd vote against this feature in its current form. Mapnik doesn't parse SQL, it just replaces certain substrings. Internal tokens like `!bbox!` are fine because mapnik can guarantee that the injected string won't be malicious.

Not so when injecting `@values` without even knowing whether it's inside a string literal, or outside in raw SQL. `attributes` are datasource-agnostic, and must be usable in filter expressions, so SQL-escaping the values before placing them in `attributes` is not an option. There's no safe way to inject a string value.

**Comment by springmeyer** [comment]
Agree that this regressed in e300a41. Sorry for overlooking that `@` could be valid in SQL, but of course they can in this case of a string that gets matched. Appreciate @lightmare for providing a workaround and larger thoughts about a better design.

My thoughts are that:

  - I'm in support of thinking about a better interface or a revert for Mapnik 3.1.x (where we can make bigger changes)
  - For Mapnik 3.0.x we could consider adapting the regex to ensure there is whitespace proceeding the `@` to avoid problems like the original issue here.
  - As far as safety, the idea is that this is not the concern of the postgis plugin but rather the application that calls Mapnik. The variables can only be populated programmatically, so if the calling application does not accept them there is no vulnerability. If that calling application does, the idea is they should be hardcoded by the developer and not based on user input. If they are based on user input then the developer should sanitizer them to prevent any chance of SQL injection. Writes are banned by the postgis connection (https://github.com/mapnik/mapnik/blob/df51f6087c509b2105b2a72d46c27fe585babe1f/plugins/input/postgis/connection.hpp#L68). However I'm definitely in support for thinking about a second defense - perhaps Mapnik should still be sanitizing the variables provided?

**Comment by lightmare** [comment]
Ad bullet 3)
The safety of `@var` is the concern of the context where it's substituted, in this case the postgis plugin and the SQL query in style XML.
It shouldn't be the concern of the calling application that fills `@var` from user input, because it can't know where in the style XML it'll be used, what kind of datasource (which governs escaping syntax) or rule filter (no escaping). The only way to make such application work with multiple styles using different datasources would be to provide escaped values in all supported flavors. Not nice.

Luckily the query obtained from style XML is considered trusted by postgis plugin, so we can just tell the user to never put `!@var!` (I'm starting to really like this form saying !danger area!) inside literals, and properly escape it in the plugin.
