### ISSUE TITLE
Binary Files not found

### ISSUE THREAD

**Issue by bleesand** [mapnik/mapnik#3675]
Installing Mapnik on Ubuntu 16.04. Encountered: 
Failed to fetch http://ppa.launchpad.net/sharpie/for-science/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/sharpie/postgis-nightly/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by donnyv** [comment]
Node mapnik can't find binaries either. https://github.com/mapnik/node-mapnik/issues/762

**Comment by springmeyer** [comment]
@bleesand the error you are hitting is unrelated to Mapnik. Mapnik is packaged in ubuntu at https://packages.ubuntu.com/source/xenial/mapnik. The error you are hitting appears to be related to a third party PPA you added (https://launchpad.net/~sharpie/+archive/ubuntu/for-science).

@donnyv - your issue is described at https://github.com/mapnik/node-mapnik/issues/762#issuecomment-304086200
