### ISSUE TITLE
PGRaster plugin

### ISSUE THREAD

**Issue by jds88y** [mapnik/mapnik#3724]
Might it be possible to include the PGRaster plugin in the pre-compiled nightly package builds?
We're having a nightmare trying to make it compile on our systems.
Thanks,
Jason

**Comment by springmeyer** [comment]
> We're having a nightmare trying to make it compile on our systems.

Yes, in my experience the circular dependency of postgis on gdal and gdal on postgres is hard, let alone building mapnik against the same gdal and postgres. Because of the challenge of installing postgis with raster support the core mapnik devs have had trouble testing and keeping working the pgraster plugin. Therefore it is planned for removal from core: #3674.

So, the answer is no: There are no plans to provide pre-compiled binaries of the plugin. If someone would like to volunteer to provide them, please post to this ticket. Until then I will close. Sorry if this is dissapointing @jds88y - Even though I can't help you, I would be interested in hearing about your usecases for the pgraster plugin. Maybe they could be solved by exporting the data to the file system and reading via the gdal plugin?
