### ISSUE TITLE
Static initialisation order fiasco 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3821]
## How to reproduce 

* Compile mapnik master (aka 3.1.x) in debug mode (DEBUG=yes) 
* Run tests

For example : 

```
./test/unit/run "topojson"
run: /opt/boost_1_65_1/include/boost/spirit/home/x3/nonterminal/rule.hpp:137: std::string boost::spirit::x3::get_info<boost::spirit::x3::rule<mapnik::json::grammar::geojson_tag, mapnik::json::geojson_value, false>, void>::operator()(const T &) const [Parser = boost::spirit::x3::rule<mapnik::json::grammar::geojson_tag, mapnik::json::geojson_value, false>, Enable = void]: Assertion `(r.name)&&("uninitialized rule")' failed.
Aborted (core dumped)

```

**Comment by artemp** [comment]
https://github.com/boostorg/spirit/pull/229 <-- background

**Comment by lightmare** [comment]
Just a note for myself and others. This issue arises from possibly unintended usage -- splitting one grammar into multiple .cpp files. It's an oversight in Spirit, as it would not be an issue if `x3::rule` constructors were `constexpr`.

As long as they're not constexpr, those `x3::rule` constants that are meant to be used from elsewhere should simply be defined in the common header. Every translation unit will have its own rule initialized before use. The only downside to this is that the "Rule name string" will appear in this header, instead of the `_def` header; in my opinion that's still nicer than explicit getter function and fiddling with dynamic initialization order.

NB: Notice that [`static` initialization order 'fiasco'](https://isocpp.org/wiki/faq/ctors#static-init-order), is not about *static initialization*. It's about *dynamic initialization* of variables with *static storage duration*. **[basic.start.init]**
