### ISSUE TITLE
Not syntax is unintuitive

### ISSUE THREAD

**Issue by larsga** [mapnik/mapnik#4108]
This works, in the sense that Ruhnu is not rendered:

```
  <Style name="islands">
    <Rule>
      <Filter>not([name] = 'Ruhnu')</Filter>
```

This does not work: Öland is still rendered:

```
  <Style name="islands">
    <Rule>
      <Filter>not([name] = 'Ruhnu') and not([name] = 'Öland')</Filter>
```

This, however, does work:

```
  <Style name="islands">
    <Rule>
      <Filter>(not([name] = 'Ruhnu')) and (not([name] = 'Öland'))</Filter>
```

Treating `not` as a function rather than as a keyword, or introducing `!=` would both be nice.

**Comment by lightmare** [comment]
> This does not work: Öland is still rendered:
> 
> ```
>   <Style name="islands">
>     <Rule>
>       <Filter>not([name] = 'Ruhnu') and not([name] = 'Öland')</Filter>
> ```

What version of Mapnik? This looks very much like an old issue that was fixed long ago (in [Mapnik 3.0.10](https://github.com/mapnik/mapnik/milestone/36?closed=1)). For the record, that issue was #3017 but is now inaccessible for some reason.

As for your final suggestion, `not` is parsed as a unary operator with precedence higher than `and/or` but lower than comparison operators, that means `not a = b and c` is equivalent to `(not (a = b)) and c`. Turning `not` into a function would make parentheses after it mandatory. We also have not-equal operator `!=`, with aliases `neq` and `<>` (don't use this one).

**Comment by larsga** [comment]
It's hard to say what version it is. I'm using it from Python, and it's python-mapnik 0.1, installed via pip. It seems to have it's own `libmapnik.dylib` that came with it.

Requiring the parentheses would be a benefit in my opinion, but OK. It sounds like this issue should be closed, then.

**Comment by lightmare** [comment]
PyPI packages have been unmaintained for quite some time, that version 0.1 predates Mapnik 3.0, so obviously doesn't have the fix I mentioned.

**Comment by larsga** [comment]
That explains why I've spent much of Christmas fighting weird bugs in python-mapnik. Ah well. We can close this, then.
