### ISSUE TITLE
boost regression 

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4235]
This issue is pulled out of #4191 to split the discussion a bit.

The minimum boost version in SCons is 1.61. However in https://github.com/mapnik/mapnik/pull/4191#issuecomment-875053928 were build failures reported (with boost version  1.66.0) 

I've tested on Ubuntu 20.04 again and had linkage errors with boost 1.71. The latest boost version that compiled successfully was 1.73. 

Linkage error with boost 1.71: 
[boost-err.txt](https://github.com/mapnik/mapnik/files/6858320/boost-err.txt)

I think we should at least support 1.65, since this is the latest version on ubuntu 18.04

**Comment by mathisloge** [comment]
#4211 is related

**Comment by craigds** [comment]
I also was getting build failures with boost 1.65 on Ubuntu 18.04 LTS (the same failures mentioned in https://github.com/mapnik/mapnik/pull/4191#issuecomment-875053928 )

Using libboost1.74 from https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest/ fixed this problem for me

**Comment by craigds** [comment]
This issue makes it quite hard to build a python-mapnik on Ubuntu 18.04

I tried using a libboost1.74 from [this PPA](https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest) which works for mapnik itself if you get the packaging right, but because there's no boost-python included there's no way to build python-mapnik with that.

**Comment by b00ga** [comment]
For reference, I'm trying to build for RHEL/CentOS 8 and your packaged options are Boost 1.66 or a parallel-installable 1.69.
