### ISSUE TITLE
scons: building terminated because of errors.

### ISSUE THREAD

**Issue by cschissler** [mapnik/mapnik#950]
Hello, I am installing mapnik2 on ubuntu os.  I am getting the following error after "sudo python scons/scons.py install".  Please advise...

---

You are compiling Mapnik trunk (aka Mapnik2)
See important details at:
http://trac.mapnik.org/wiki/Mapnik2

---

Notice: dependencies not met for plugin 'occi', not building...
Notice: dependencies not met for plugin 'rasterlite', not building...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/mapped_memory_cache.os -c -DHAVE_JPEG -DBOOST_REGEX_HAS_ICU -ansi -Wall -pthread -ftemplate-depth-300 -DLINUX -DBOOST_SPIRIT_THREADSAFE -DMAPNIK_THREADSAFE -O3 -finline-functions -Wno-inline -DNDEBUG -DHAVE_CAIRO -fPIC -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/cairomm-1.0 -I/usr/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -Iagg/include -I. -Iinclude -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql src/mapped_memory_cache.cpp
In file included from /usr/include/boost/interprocess/detail/utilities.hpp:29:0,
                 from /usr/include/boost/interprocess/mapped_region.hpp:20,
                 from include/mapnik/mapped_memory_cache.hpp:34,
                 from src/mapped_memory_cache.cpp:26:
/usr/include/boost/interprocess/detail/transform_iterator.hpp:57:15: error: reference ‘m_value’ cannot be declared ‘mutable’ [-fpermissive]
scons: **\* [src/mapped_memory_cache.os] Error 1
scons: building terminated because of errors.

**Comment by VigneshwaranRM** [comment]
Hi, 

I'm Getting this error while building with with scon.. Could someone help me to resolve this ?

~/SandBox$ scons
scons: Reading SConscript files ...

scons: warning: Ignoring missing SConscript 'controller/SConscript'
File "/home/vigneshwaran/SandBox/SConstruct", line 16, in <module>

scons: warning: Ignoring missing SConscript 'build/noarch/nova_contrail_vif/SConscript'
File "/home/vigneshwaran/SandBox/SConstruct", line 19, in <module>

scons: warning: Ignoring missing SConscript 'build/noarch/neutron_plugin/SConscript'
File "/home/vigneshwaran/SandBox/SConstruct", line 26, in <module>
scons: done reading SConscript files.
scons: Building targets ...
o build/debug/tools/sandesh/compiler/main.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/main.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/sandeshy.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include build/debug/tools/sandesh/compiler/sandeshy.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/sandeshl.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include build/debug/tools/sandesh/compiler/sandeshl.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_cpp_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_cpp_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_html_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_html_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_xsd_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_xsd_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_c_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_c_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/generate/t_py_generator.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/generate/t_py_generator.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/parse/parse.o -c -g -O0 -DDEBUG -DSANDESH -Itools/sandesh/compiler -Ibuild/include tools/sandesh/compiler/parse/parse.cc
sh: 1: o: not found
o build/debug/tools/sandesh/compiler/sandesh -g build/debug/tools/sandesh/compiler/main.o build/debug/tools/sandesh/compiler/md5.o build/debug/tools/sandesh/compiler/sandeshy.o build/debug/tools/sandesh/compiler/sandeshl.o build/debug/tools/sandesh/compiler/generate/t_cpp_generator.o build/debug/tools/sandesh/compiler/generate/t_html_generator.o build/debug/tools/sandesh/compiler/generate/t_generator.o build/debug/tools/sandesh/compiler/generate/t_xsd_generator.o build/debug/tools/sandesh/compiler/generate/t_c_generator.o build/debug/tools/sandesh/compiler/generate/t_py_generator.o build/debug/tools/sandesh/compiler/parse/parse.o
sh: 1: o: not found
Install file: "build/debug/tools/sandesh/compiler/sandesh" as "build/bin/sandesh"
scons: *** [build/bin/sandesh] build/debug/tools/sandesh/compiler/sandesh: No such file or directory
scons: building terminated because of errors.

**Comment by springmeyer** [comment]
@VigneshwaranRM it does not look like you are trying to build Mapnik. Mapnik uses scons but your problem does not look like a problem with Mapnik. So you should contact the author of the software you are trying to build. The issues appears to be related to the compiler not being set.

**Comment by VigneshwaranRM** [comment]
Hi Springmeyer,

I resolved those errors and successfully build the system. Thanks.

I done this build for opencontrail. Now I need to know how to proceed further for installing and accessing Opencontrail GUI. If you know please let me know.

Thank you

**Comment by avirupd-egnaroinc** [comment]
Hi Springmeyer,

git clone git://github.com/mapnik/mapnik
cd mapnik
git branch 2.2 origin/2.2.x
git checkout 2.2
python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/truetype/
sudo make install

After this I am getting scons: building terminated because of errors.
make: *** [install] Error 2

I have tried to solve this by using sudo apt-get upgrade, sudo apt-get autoremove
But this does not help. Still getting the same error. Please help me with this.

Thanks
