### ISSUE TITLE
north up restriction wrongly applied to valid north-up dataset when using gdal 1.9dev

### ISSUE THREAD

**Issue by oeon** [mapnik/mapnik#970]
I ran `brew install gdal --HEAD` after editing the default formula, with these small changes https://gist.github.com/1407046 lines 88,89 were changed from 'internal' to '/usr/local/lib' and line 100 was commented out to avoid this error https://github.com/mxcl/homebrew/issues/8301 (sorry I could not do a 'cooler' diff, still learning...here's a gist of `diff -u ~/gdal.rb /usr/local/Library/Formula/gdal.rb > gdal_diff`) https://gist.github.com/1407084 but I described it completely above.

When adding a raster that is know to work in the TileMill 0.7.0 installer, the application reports a "Error: GDAL Plugin: only 'north up' images are supported" error ... the terminal reports "ERROR 1: Only OGC WKT Projections supported for writing to GeoTIFF. ??d? not supported."

example raster (EPSG:3785) https://s3-us-west-1.amazonaws.com/tmill/slohlsd2_clp.tif

**Comment by letmaik** [comment]
@springmeyer The link you posted doesn't work anymore. Is the downstream issue documented anywhere else?

**Comment by springmeyer** [comment]
@letmaik no it is not - that info is lost. But this should have been worked-around/fixed in https://github.com/mapnik/mapnik/commit/1fa26fa067474272d2a0d9ba31e840f11c2fe14f. If you are still seeing a problem please create a new ticket and provide a testcase: https://github.com/mapnik/mapnik/wiki/A-perfect-testcase
